[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.12.0", features = ["attributes"] }
sqlx = { version = "0.8.3", features = ["runtime-async-std", "mysql"] }
